# Generated by Django 4.1.3 on 2024-09-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_immobile_registerlocation_immobileimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conteudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_1", models.CharField(max_length=255)),
                ("titulo_2", models.CharField(blank=True, max_length=255, null=True)),
                ("descricao_1", models.TextField(blank=True, null=True)),
                ("descricao_2", models.TextField(blank=True, null=True)),
                ("imagem", models.ImageField(upload_to="banners/")),
                (
                    "titulo_botao_1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "rota_botao_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "titulo_botao_2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "rota_botao_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="registerlocation",
            options={
                "ordering": ["-create_at"],
                "verbose_name": "Registrar Locação",
                "verbose_name_plural": "Registrar Locação",
            },
        ),
    ]
